version: "3.4"

x-common-config:
  &common-config
  volumes:
    -  ./conf:/etc/hadoop/conf
    -  ${HADOOP_BUILD_PATH}:/hadoop
    -  /mnt/data
  build: ../  

services:
  nn:
    <<: *common-config
    environment:
      - ENSURE_NAMENODE_DIR=/mnt/data/nn/current
    ports:
      - "9870:9870"
    command: hdfs namenode

  snn:
    <<: *common-config
    environment:
      - WAITFOR=nn:8020
      - ENSURE_SECONDARY_NAMENODEDIR=/mnt/data/snn/current
    ports:
      - "9871:9870"
    command: hdfs secondarynamenode

  dn:
    <<: *common-config
    command: hdfs datanode  
