version: "3.4"

x-common-config:
  &common-config
  volumes:
    -  ${HADOOP_BUILD_PATH}:/hadoop
    -  /mnt/data
  build: ../  
  image: hadoop-docker

x-common-environment: &common-environment
  ENV2CONF_hdfs-site.xml: /etc/hadoop/conf
  ENV2CONF_core-site.xml: /etc/hadoop/conf
  core-site.xml_fs.defaultFS: hdfs://nn1
  hdfs-site.xml_dfs.namenode.name.dir: /mnt/data/nn
  hdfs-site.xml_dfs.namenode.checkpoint.dir: /mnt/data/snn
  hdfs-site.xml_dfs.namenode.acls.enabled: "true"
  hdfs-site.xml_datanode.data.dir: /mnt/data/dn
  hdfs-site.xml_fs.trash.interval: 10
  hdfs-site.xml_dfs.namenode.hosts.provider.classname: org.apache.hadoop.hdfs.server.blockmanagement.CombinedHostFileManager
  hdfs-site.xml_dfs.hosts: /tmp/dfshosts

services:
  nn1:
    <<: *common-config
    environment:
      <<: *common-environment
      ENSURE_NAMENODE_DIR: /mnt/data/nn/current
    ports:
      - "9870:9870"
    command: hdfs namenode

  snn:
    <<: *common-config
    environment:
      <<: *common-environment            
      WAITFOR: nn:8020
      ENSURE_SECONDARY_NAMENODEDIR: /mnt/data/snn/current  
    ports:
      - "9871:9870"
    command: hdfs secondarynamenode

  dn:
    <<: *common-config
    environment:
      <<: *common-environment      
    command: hdfs datanode  
