version: "3.4"

x-common-config:
  &common-config
  volumes:
    -  ./conf:/etc/hadoop/conf
    -  ${HADOOP_BUILD_PATH}:/hadoop
    -  /mnt/data
  build: ../  

services:
  nn1:
    <<: *common-config
    environment:
      - ENSURE_NAMENODE_DIR=/mnt/data/nn/current
    ports:
      - "9870:9870"
    depends_on:
      - jn1
      - jn2
      - jn3
    command: hdfs namenode

  nn2:
    <<: *common-config
    environment:
      - WAITFOR=nn1:8020
      - BOOTSTRAP_STANDBY_DIR=/mnt/data/nn/current
      - MAKE_NN_ACTIVE=nn1
    ports:
      - "9871:9870"
    depends_on:
      - nn1
      - jn1
      - jn2
      - jn3
    command: hdfs namenode

# Cannot just use one JN service and scale it, as the hostnames it creates are
# jn_1, jn_2, jn_3 and these are invalid hostnames. The NN refuses to connect to
# them due to the illegal underscore character in the filename.
  jn1:
    <<: *common-config
    command: hdfs journalnode

  jn2:
    <<: *common-config
    command: hdfs journalnode

  jn3:
    <<: *common-config
    command: hdfs journalnode
  
  dn:
    <<: *common-config
    command: hdfs datanode  
